import { createDefaultLlmConfig } from "../llm/config";
import type { ConfigLabPayload, ConfigLabSummaryMetric } from "./types";
import {
  getConfigLabPresetPack,
  getDefaultConfigLabPresetPackId,
  listConfigLabPresetPacks,
} from "./presets";

const DEFAULT_CONFIG_LAB_SUMMARY: ConfigLabSummaryMetric[] = [
  {
    label: "Preset packs",
    value: "4 ready",
    detail: "Baseline, pressure, endgame, and benchmark packs",
    tone: "positive",
  },
  {
    label: "Backends",
    value: "Hybrid",
    detail: "Native, Tauri, HTTP, and browser fallback summaries",
    tone: "neutral",
  },
  {
    label: "Privacy",
    value: "Strict local",
    detail: "LLM stays disabled until you opt in",
    tone: "positive",
  },
  {
    label: "Bench readiness",
    value: "Partial",
    detail: "Native parity is ready; offline harnesses stay queued",
    tone: "warning",
  },
];

const DEFAULT_LLM_CONFIG = createDefaultLlmConfig();
const DEFAULT_BACKENDS: ConfigLabPayload["backends"] = [
  {
    id: "native_rust",
    kind: "native_rust",
    label: "Native Rust engine",
    state: "unknown",
    healthy: false,
    source: "fallback",
    reason: "Awaiting a runtime snapshot.",
    latencyMs: null,
    supportsSolve: true,
    supportsBenchmarks: true,
    supportsCopilot: false,
    preferred: true,
  },
  {
    id: "tauri_host",
    kind: "tauri_host",
    label: "Tauri host",
    state: "unknown",
    healthy: false,
    source: "fallback",
    reason: "Awaiting a desktop host.",
    latencyMs: null,
    supportsSolve: true,
    supportsBenchmarks: true,
    supportsCopilot: true,
    preferred: false,
  },
  {
    id: "http_server",
    kind: "http_server",
    label: "Local HTTP server",
    state: "unknown",
    healthy: false,
    source: "fallback",
    reason: "Awaiting a local REST runtime.",
    latencyMs: null,
    supportsSolve: true,
    supportsBenchmarks: true,
    supportsCopilot: true,
    preferred: false,
  },
  {
    id: "browser_fallback",
    kind: "browser_fallback",
    label: "Browser fallback",
    state: "ready",
    healthy: true,
    source: "fallback",
    reason: "Deterministic offline payloads are always available.",
    latencyMs: 0,
    supportsSolve: false,
    supportsBenchmarks: false,
    supportsCopilot: true,
    preferred: false,
  },
];

const DEFAULT_BENCHMARK_SUITES: ConfigLabPayload["benchmarkSuites"] = [
  {
    id: "native_solve",
    label: "Native solve parity",
    description: "Validate the local Rust solve path against known fixtures and cached spots.",
    state: "queued",
    ready: false,
    coverage: 45,
    requiredTools: ["native rust engine", "solver-studio fixtures"],
    notes: ["Primary V2 solve path should remain the first benchmark gate."],
  },
  {
    id: "http_parity",
    label: "HTTP parity",
    description: "Confirm the local HTTP fallback returns the same normalized decision shape.",
    state: "queued",
    ready: false,
    coverage: 35,
    requiredTools: ["local REST runtime", "normalization bridge"],
    notes: ["Useful for isolation, debugging, and host fallback verification."],
  },
  {
    id: "pokerkit_validation",
    label: "PokerKit validation",
    description: "Replay and rules-check harness for legal actions, streets, and side-pot safety.",
    state: "queued",
    ready: false,
    coverage: 0,
    requiredTools: ["PokerKit oracle", "replay fixtures"],
    notes: ["Queued until the validation harness is wired into the app."],
  },
  {
    id: "rlcard_offline",
    label: "RLCard offline",
    description: "Offline self-play and policy comparison loop for long-running study jobs.",
    state: "queued",
    ready: false,
    coverage: 0,
    requiredTools: ["RLCard", "seeded offline jobs"],
    notes: ["Useful for regression tracking and learning experiments."],
  },
  {
    id: "llm_assist_smoke",
    label: "LLM assist smoke",
    description: "Optional OpenAI-format copilot smoke test for explanations and operator help.",
    state: "disabled",
    ready: false,
    coverage: 0,
    requiredTools: ["optional LLM provider", "privacy-safe context routing"],
    notes: ["Disabled until the copilot is explicitly enabled."],
  },
];

export const DEFAULT_CONFIG_LAB_PAYLOAD: ConfigLabPayload = {
  id: "config-lab-default",
  generatedAt: new Date(0).toISOString(),
  runtimeSource: "fallback",
  appName: "PokerMaster",
  version: "v2",
  runtime: "browser",
  status: "offline",
  healthy: false,
  devMode: false,
  uptimeMs: 0,
  selectedPresetPackId: getDefaultConfigLabPresetPackId(),
  presetPacks: listConfigLabPresetPacks(),
  activePresetPack: getConfigLabPresetPack(getDefaultConfigLabPresetPackId()),
  llm: {
    enabled: false,
    providerMode: "disabled",
    providerLabel: "Disabled",
    privacyMode: "strict_local",
    privacyLabel: "Strict local",
    baseUrl: DEFAULT_LLM_CONFIG.baseUrl,
    apiKeyRef: "",
    model: DEFAULT_LLM_CONFIG.model,
    temperature: DEFAULT_LLM_CONFIG.temperature,
    maxOutputTokens: DEFAULT_LLM_CONFIG.maxOutputTokens,
    streaming: false,
    rolesEnabled: { ...DEFAULT_LLM_CONFIG.rolesEnabled },
    contextScopesEnabled: { ...DEFAULT_LLM_CONFIG.contextScopesEnabled },
    activeRoles: [],
    activeScopes: [],
    roleCount: 0,
    scopeCount: 0,
    networkRequired: false,
    posture: "disabled",
  },
  backends: DEFAULT_BACKENDS.map((backend) => ({ ...backend })),
  benchmarkSuites: DEFAULT_BENCHMARK_SUITES.map((suite) => ({
    ...suite,
    requiredTools: [...suite.requiredTools],
    notes: [...suite.notes],
  })),
  benchmarkReadiness: {
    state: "partial",
    ready: false,
    coverageScore: 20,
    lastRunAt: null,
    notes: ["No runtime snapshot loaded yet.", "Offline fallback remains available."],
    blockedBy: [],
    recommendedActions: [
      "Connect the local host or Tauri shell.",
      "Load the runtime snapshot to refresh backend and benchmark status.",
    ],
  },
  summary: [...DEFAULT_CONFIG_LAB_SUMMARY],
  warnings: ["offline fallback payload"],
};

export function createDefaultConfigLabPayload(
  overrides: Partial<ConfigLabPayload> = {}
): ConfigLabPayload {
  return {
    ...DEFAULT_CONFIG_LAB_PAYLOAD,
    presetPacks: DEFAULT_CONFIG_LAB_PAYLOAD.presetPacks.map((pack) => ({
      ...pack,
      treePresetIds: [...pack.treePresetIds],
      benchmarkSuites: [...pack.benchmarkSuites],
      tags: [...pack.tags],
    })),
    activePresetPack: {
      ...DEFAULT_CONFIG_LAB_PAYLOAD.activePresetPack,
      treePresetIds: [...DEFAULT_CONFIG_LAB_PAYLOAD.activePresetPack.treePresetIds],
      benchmarkSuites: [...DEFAULT_CONFIG_LAB_PAYLOAD.activePresetPack.benchmarkSuites],
      tags: [...DEFAULT_CONFIG_LAB_PAYLOAD.activePresetPack.tags],
    },
    backends: DEFAULT_CONFIG_LAB_PAYLOAD.backends.map((backend) => ({ ...backend })),
    benchmarkSuites: DEFAULT_CONFIG_LAB_PAYLOAD.benchmarkSuites.map((suite) => ({
      ...suite,
      requiredTools: [...suite.requiredTools],
      notes: [...suite.notes],
    })),
    benchmarkReadiness: {
      ...DEFAULT_CONFIG_LAB_PAYLOAD.benchmarkReadiness,
      notes: [...DEFAULT_CONFIG_LAB_PAYLOAD.benchmarkReadiness.notes],
      blockedBy: [...DEFAULT_CONFIG_LAB_PAYLOAD.benchmarkReadiness.blockedBy],
      recommendedActions: [...DEFAULT_CONFIG_LAB_PAYLOAD.benchmarkReadiness.recommendedActions],
    },
    llm: {
      ...DEFAULT_CONFIG_LAB_PAYLOAD.llm,
      rolesEnabled: { ...DEFAULT_CONFIG_LAB_PAYLOAD.llm.rolesEnabled },
      contextScopesEnabled: { ...DEFAULT_CONFIG_LAB_PAYLOAD.llm.contextScopesEnabled },
      activeRoles: [...DEFAULT_CONFIG_LAB_PAYLOAD.llm.activeRoles],
      activeScopes: [...DEFAULT_CONFIG_LAB_PAYLOAD.llm.activeScopes],
    },
    summary: DEFAULT_CONFIG_LAB_PAYLOAD.summary.map((metric) => ({ ...metric })),
    warnings: [...DEFAULT_CONFIG_LAB_PAYLOAD.warnings],
    ...overrides,
  };
}
