#!/bin/sh

version_mode=0
exists_mode=0
pkg_name=""

for arg in "$@"; do
  case "$arg" in
    --version|--modversion)
      version_mode=1
      ;;
    --exists)
      exists_mode=1
      ;;
    --*)
      ;;
    *)
      if [ -z "$pkg_name" ]; then
        pkg_name=$arg
      fi
      ;;
  esac
done

if [ "$version_mode" -eq 1 ]; then
  printf '%s\n' "1.0.0"
  exit 0
fi

if [ "$exists_mode" -eq 1 ]; then
  exit 0
fi

pkg_name=${pkg_name%% *}
case "$pkg_name" in
  "" ) pkg_name="system" ;;
esac

printf '%s\n' "-I/usr/include -L/usr/lib -l${pkg_name}"
