name: Binary Release Windows

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          show-progress: false

      - name: Set up Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.11
    

      - name: Install Tesseract
        run: |
          iwr https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.6.0-tesseract-5.3.1/tesserocr-2.6.0-cp311-cp311-win_amd64.whl -Out tesserocr-2.6.0-cp311-cp311-win_amd64.whl
          pip install tesserocr-2.6.0-cp311-cp311-win_amd64.whl

      - name: Install dependencies
        run: pip install -e .

      - name: Run PyInstaller
        run: |
          cd poker
          pyinstaller main.spec

      - name: Prepare distribution
        run: |
          cd poker
          mkdir dist\main\log
          mkdir dist\main\pics
          mkdir dist\main\log\screenshots
          xcopy icon.ico dist\main\poker.ico* /Y
          xcopy config_default.ini dist\main\config.ini* /Y
          xcopy vboxapi dist\main\vboxapi\ /E

      - name: Install NSIS
        run: |
          choco install nsis

      - name: Run NSIS
        run: |
          makensis -V3 poker\DeepMindPokerbot.nsi
         
      - name: Create Release and upload asset
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          tag_name: DeepermindPokerbot-${{ github.run_number }}
          name: Windows Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: ./DeepMindPokerbot_winstaller.exe
