name: Binary Release for MacOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.11
          cache: pip

      - name: Install dependencies
        run: pip install -e .

      - name: Run PyInstaller for MacOS
        run: |
          cd poker
          pyinstaller --noconfirm --clean --distpath dist/main main.spec

      - name: Prepare distribution for MacOS
        run: |
          cd poker
          mkdir -p dist/main/log
          mkdir -p dist/main/pics
          mkdir -p dist/main/log/screenshots
          cp icon.ico dist/main/poker.ico
          cp config_default.ini dist/main/config.ini
          cp -r vboxapi dist/main/vboxapi/

      - name: Install create-dmg
        run: npm install -g create-dmg

      - name: List contents of PyInstaller output directory
        run: |
          cd poker/dist/main
          ls

      - name: Create DMG
        run: |
          cd poker/dist/main
          create-dmg DeepMindPokerbot.dmg .

      - name: Create Release for MacOS and upload DMG
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          tag_name: DeepermindPokerbot-mac-${{ github.run_number }}
          name: Mac Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: /Users/runner/work/Poker/Poker/dist/main/DeepMindPokerbot.dmg
  
